---
- name: Started and Enabled NGINX
  service:
    name: nginx
    enabled: yes 
    state: started

- name: Restart Firewalld
  service: 
    name: firewalld 
    state: restarted

- name: Started and Enabled PHP-FPM
  service:
    name: php-fpm 
    enabled: yes 
    state: started

- name: Restart NGINX
  service: 
    name: nginx 
    state: restarted

- name: Restart PHP-FPM
  service: 
    name: php-fpm
    state: restarted







    