---
- name: Editing file "config.php"
  template: 
    src: config.php.j2
    dest: "{{ path_moodle_project }}/moodle/config.php"

- name: Configuring NGINX for Moodle
  template:
    src: moodle.conf.j2
    dest: "{{ path_moodle_conf }}"
  notify: 
    - Restart NGINX
    - Restart PHP-FPM